server:
  port: 9998

spring:
   boot:
     admin:
       client:
          url: http://localhost:9999
          instance:
            prefer-ip: true

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
